Introduce `NetworkConfig` on Android
bitmovin/bitmovin-player-react-native pull request #452
Opened 2024-05-29 12:46 UTC by rolandkakonyi

## Description

## Changes

## Checklist
- [ ] 🗒 `CHANGELOG` entry

2024-05-29 12:56 UTC, rolandkakonyi commented on android/build.gradle
> +    implementation "androidx.concurrent:concurrent-futures-ktx:1.1.0"
This is necessary for using `CallbackToFutureAdapter` in `NetworkModule.kt`

2024-05-29 16:44 UTC, 123mpozzi commented on android/src/main/java/com/bitmovin/player/reactnative/converter/JsonConverter.kt
> +}
To add context here: I went for `Base64.NO_WRAP` as apparently `Base64.DEFAULT` adds a line break

2024-05-29 18:07 UTC, 123mpozzi reviewed
The code seems to be working 💪 
However I am no expert in Kotlin so I cannot comment the style 😅 : I see we use this `Completer` which is very similar to what we do in the iOS counterpart.

---

I am also leaving some additional notes to things we should look for:
- testing performance on a real device
- testing base64 encoding/decoding: to me it looks like the `body` fields here are bigger than in the iOS counterpart

2024-06-03 10:04 UTC, rolandkakonyi commented
> * testing base64 encoding/decoding: to me it looks like the `body` fields here are bigger than in the iOS counterpart

@123mpozzi what do you mean here by `body` fields are bigger?
We can't really compare as iOS and Android loads different manifests (HLS vs DASH) AND additionally Android supports video and audio segments with the network API, while iOS doesn't.

2024-06-03 10:11 UTC, matamegger requested changes
Looks good overall 👍

2024-06-03 10:15 UTC, rolandkakonyi commented on android/src/main/java/com/bitmovin/player/reactnative/NetworkModule.kt
> +    }
Good catch! Fixed in edf371a0

2024-06-03 10:29 UTC, rolandkakonyi commented on android/src/main/java/com/bitmovin/player/reactnative/BitmovinBaseModule.kt
> +        ?: throw IllegalArgumentException("Invalid NetworkId $nativeId")
Removed in 625594f2

2024-06-03 10:42 UTC, rolandkakonyi commented on android/src/main/java/com/bitmovin/player/reactnative/NetworkModule.kt
> +    }
I tried to use a single lock to wrap all writing of all of those maps but it affects the playback performance.

Do you maybe have a suggestion how could this be implemented in a performant way?

2024-06-03 10:44 UTC, rolandkakonyi commented on android/build.gradle
> +    implementation "androidx.concurrent:concurrent-futures-ktx:1.1.0"
Added the missing dependency here: b0222168

2024-06-03 10:57 UTC, rolandkakonyi commented on android/src/main/java/com/bitmovin/player/reactnative/NetworkModule.kt
> +    }
As discussed offline, let's keep this as is for now.

2024-06-03 11:34 UTC, rolandkakonyi commented on android/src/main/java/com/bitmovin/player/reactnative/PlayerModule.kt
> +        networkNativeId?.let { networkModule.getConfig(it) }?.let { playerConfig.networkConfig = it }
Improved in a9685d8b

2024-06-03 12:14 UTC, 123mpozzi commented
> > * testing base64 encoding/decoding: to me it looks like the `body` fields here are bigger than in the iOS counterpart
> 
> @123mpozzi what do you mean here by `body` fields are bigger? We can't really compare as iOS and Android loads different manifests (HLS vs DASH) AND additionally Android supports video and audio segments with the network API, while iOS doesn't.

I see, then the difference makes sense 👍

2024-06-03 12:52 UTC, merged