Prn 147/expose tweaks config force reuse video codec reasons
bitmovin/bitmovin-player-react-native pull request #561
Opened 2024-11-14 07:44 UTC by saravanans-github

## Description
Expose Android SDKs TweaksConfig.forceReuseVideoCodecReasons
## Changes

## Checklist
- [ ] 🗒 `CHANGELOG` entry

2024-11-14 12:57 UTC, krocard requested changes
I didn't test the PR, just reviewed the code change.

2024-11-14 12:57 UTC, krocard commented on android/src/main/java/com/bitmovin/player/reactnative/converter/JsonConverter.kt
> +    }
```suggestion
        forceReuseVideoCodecReasons = it.mapNotNull(String::forceReuseVideoCodecReason)
```

2024-11-14 12:57 UTC, krocard commented on src/tweaksConfig.ts
> +   *
```suggestion
   *
   * If a device is know to support video format changes and keep the current decoder without issues,
   * this set can be filled with multiple `ForceReuseVideoCodecReason` and avoid the black screen.
   *
```

2024-11-14 12:57 UTC, krocard commented on android/src/main/java/com/bitmovin/player/reactnative/converter/JsonConverter.kt
> +private fun String.forceReuseVideoCodecReason(): ForceReuseVideoCodecReason? = when (this) {
```suggestion
private fun String.toForceReuseVideoCodecReason(): ForceReuseVideoCodecReason? = when (this) {
```

2024-11-14 12:57 UTC, krocard commented on android/src/main/java/com/bitmovin/player/reactnative/converter/JsonConverter.kt
> + * Converts any JS string into an `AdSourceType` enum value.
```suggestion
 * Converts any JS string into an `ForceReuseVideoCodecReason` enum value.
```

2024-11-14 13:48 UTC, matamegger requested changes

2024-11-14 13:54 UTC, strangesource commented
Thanks for the reviews, I'll pick this up tomorrow.

2024-11-15 11:59 UTC, strangesource commented on android/src/main/java/com/bitmovin/player/reactnative/converter/JsonConverter.kt
> +    }
[6c0fe0b](https://github.com/bitmovin/bitmovin-player-react-native/pull/561/commits/6c0fe0be72537d83455ef8ef5378a17d315bcd97)

2024-11-15 11:59 UTC, strangesource commented on android/src/main/java/com/bitmovin/player/reactnative/converter/JsonConverter.kt
> +private fun String.forceReuseVideoCodecReason(): ForceReuseVideoCodecReason? = when (this) {
[6c0fe0b](https://github.com/bitmovin/bitmovin-player-react-native/pull/561/commits/6c0fe0be72537d83455ef8ef5378a17d315bcd97)

2024-11-15 11:59 UTC, strangesource commented on android/src/main/java/com/bitmovin/player/reactnative/converter/JsonConverter.kt
> + * Converts any JS string into an `AdSourceType` enum value.
[6c0fe0b](https://github.com/bitmovin/bitmovin-player-react-native/pull/561/commits/6c0fe0be72537d83455ef8ef5378a17d315bcd97)

2024-11-15 11:59 UTC, strangesource commented on android/src/main/java/com/bitmovin/player/reactnative/converter/JsonConverter.kt
> +private fun String.forceReuseVideoCodecReason(): ForceReuseVideoCodecReason? = when (this) {
[6c0fe0b](https://github.com/bitmovin/bitmovin-player-react-native/pull/561/commits/6c0fe0be72537d83455ef8ef5378a17d315bcd97)

2024-11-15 12:00 UTC, strangesource commented on src/tweaksConfig.ts
> +   */
[0ec9d98](https://github.com/bitmovin/bitmovin-player-react-native/pull/561/commits/0ec9d9803d26f4617e9aa96bcc608edf4864c50c)

2024-11-15 12:00 UTC, strangesource commented on src/tweaksConfig.ts
> +
[0ec9d98](https://github.com/bitmovin/bitmovin-player-react-native/pull/561/commits/0ec9d9803d26f4617e9aa96bcc608edf4864c50c)

2024-11-15 12:00 UTC, strangesource commented on src/tweaksConfig.ts
> +   *
[0ec9d98](https://github.com/bitmovin/bitmovin-player-react-native/pull/561/commits/0ec9d9803d26f4617e9aa96bcc608edf4864c50c)

2024-11-15 12:06 UTC, matamegger approved these changes
@strangesource Please revisit the Changelog entry

2024-11-15 13:52 UTC, krocard approved these changes

2024-11-15 14:14 UTC, merged